#node js app with redis DB. For views counting app.
version: '3'
services:
   redis-server:
     image: 'redis'

   node-app:
     restart: on-failure
     build: .
     ports:
       - "8800-8890:6000"

